# Generated by Django 6.0.6 on 2026-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/400', max_length=1000, null=True),
        ),
    ]
